### ISSUE TITLE
Ionic2 throw error

### ISSUE THREAD

**Issue by 7NT** [uttesh/ng2letteravatar#5]
Trying to implement ng2letteravatar into my Ionic2 project.

modified my app.module.ts:
1) import { Ng2LetterAvatar } from "ng2letteravatar/ng2letteravatar";
2) @NgModule({
  declarations: [
    MyApp,
    Ng2LetterAvatar
  ],

Got error:
Uncaught TypeError: (void 0) is not a function
    at Object.<anonymous> (main.js:126901)
    at __webpack_require__ (bootstrap 2118c8b…:19)
    at Object.<anonymous> (platform-browser-dynamic.es5.js:170)
    at __webpack_require__ (bootstrap 2118c8b…:19)
    at Object.<anonymous> (setImmediate.js:186)
    at __webpack_require__ (bootstrap 2118c8b…:19)
    at bootstrap 2118c8b…:65
    at bootstrap 2118c8b…:65

**Comment by kanak-infoObjects** [comment]
Getting the same error!

**Comment by uttesh** [comment]
Hi,

I'll look into that issue in the coming weekend.

Thanks.
Uttesh

**Comment by 78lab** [comment]
Getting the same error!

**Comment by MikeMatusz** [comment]
I'm not using Ionic, but I am using webpack, and I'm running into a similar issue, or at least it looks like it might have the same cause as this one.  My error is at runtime: "Error: Unexpected value 'Ng2LetterAvatar' declared by the module 'MyModule'".  But I'm pretty sure the root cause is that this library lists it's @angular npm dependencies in the "dependencies" section, and they're set to "2.0.0".  If my application uses a version other than 2.0.0 (such as 4.0.1) webpack essentially is decorating the Ng2LetterAvatar directive with the 2.x version of @Directive/@Component instead of the 4.x version.

Can you specify the @angular dependencies as peerDependencies (or devDependencies) instead?  And maybe also change the version in package.json to allow a range (including 4.x ideally) rather than just 2.0.0 specifically?

**Comment by anderl80** [comment]
![grafik](https://cloud.githubusercontent.com/assets/23196828/26529661/769cd8b4-43c4-11e7-9ce4-d92ef865c87c.png)
Same error

**Comment by uttesh** [comment]
@anderl80 @7NT @kanak-infoObjects @78lab @MikeMatusz 

This component is moved to ngu-utility module https://github.com/uttesh/ngu-utility and all issues are addressed.
